// import localFont from "next/font/local";
import "./globals.css";
import { Analytics } from '@vercel/analytics/react';
import Footer from "./layout/Footer";
import Navbar from "./layout/Navbar";

export const metadata = {
  title: "ICONIKQ | Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Default Favicon */}
        <link rel="icon" href="/images/favicon.ico" sizes="any" type="image/x-icon" />

        {/* Apple Touch Icon */}
        <link rel="apple-touch-icon" href="/images/apple-touch-icon.png" sizes="180x180" />

        {/* Android Icons */}
        <link rel="icon" href="/images/android-chrome-192x192.png" sizes="192x192" type="image/png" />
        <link rel="icon" href="/images/android-chrome-512x512.png" sizes="512x512" type="image/png" />

        {/* Favicons for Standard Browsers */}
        <link rel="icon" href="/images/favicon-32x32.png" sizes="32x32" type="image/png" />
        <link rel="icon" href="/images/favicon-16x16.png" sizes="16x16" type="image/png" />

        {/* Manifest (optional if you have a web app manifest) */}
        <link rel="manifest" href="/site.webmanifest" />

        {/* Google Font Import for Raleway */}
        <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@100;400;700;900&display=swap" rel="stylesheet" />
      </head>
      <body className="antialiased">
        <Navbar/>
        {children}
        <Analytics />
        <Footer/>
      </body>
    </html>
  );
}
