import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/Playfair.ttf",
  variable: "--font-headline",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/Lora.ttf",
  variable: "--font-content",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
