import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/Playfair.ttf",
  variable: "--font-headline",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/Lora.ttf",
  variable: "--font-content",
  weight: "100 900",
});

export const metadata = {
  title: "ICONIKQ | Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <head>
        {/* Default Favicon */}
        <link rel="icon" href="/images/favicon.ico" sizes="any" type="image/x-icon" />

        {/* Apple Touch Icon */}
        <link rel="apple-touch-icon" href="/images/apple-touch-icon.png" sizes="180x180" />

        {/* Android Icons */}
        <link rel="icon" href="/images/android-chrome-192x192.png" sizes="192x192" type="image/png" />
        <link rel="icon" href="/images/android-chrome-512x512.png" sizes="512x512" type="image/png" />

        {/* Favicons for Standard Browsers */}
        <link rel="icon" href="/images/favicon-32x32.png" sizes="32x32" type="image/png" />
        <link rel="icon" href="/images/favicon-16x16.png" sizes="16x16" type="image/png" />

        {/* Manifest (optional if you have a web app manifest) */}
        <link rel="manifest" href="/site.webmanifest" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
