const cardData = [
    {
      image: 'images/transport.jpg',
      title: 'EPR Registration',
      passage1:"Overview of EPR Registration: The Extended Producer Responsibility (EPR) Registration Certificate is a legal document issued to producers and importers of goods, signifying their compliance with EPR regulations. EPR mandates that these entities take responsibility for the entire lifecycle of their products, particularly regarding waste management and recycling. This certification is crucial in promoting sustainable practices, as it ensures that producers actively contribute to reducing environmental impact by managing the disposal and recycling of their products.",
      passage2:"Benefits of EPR Registration: Obtaining an EPR Registration Certificate offers numerous benefits. Firstly, it enhances a company's reputation by demonstrating commitment to sustainability and corporate social responsibility, which can attract environmentally conscious consumers. Secondly, compliance with EPR regulations can lead to cost savings through efficient waste management practices and potential incentives from governmental programs. Lastly, it facilitates access to new markets, as many regions now require EPR compliance for business operations, allowing companies to expand their reach while adhering to environmental standards.",
      description: 'The EPR Registration Certificate confirms compliance with Extended Producer Responsibility regulations, promoting sustainable product management. It enhances reputation, saves costs, and opens market access, showcasing a commitment to environmental responsibility.',
      link: 'Legal', // replace with actual link when available
    },
    {
      image: 'images/freight forwarder.png',
      title: 'BIS Certification',
      passage1:"Overview of BIS Registration: The Bureau of Indian Standards (BIS) Registration Certificate is an official document that verifies a product's compliance with Indian quality and safety standards. This certification ensures that products meet specific requirements set by BIS, promoting consumer safety and enhancing product reliability in the market. It is essential for manufacturers and importers looking to establish credibility and trust among consumers.",
      passage2:"Benefits of BIS Registration: Obtaining a BIS Registration Certificate provides several advantages. It enhances consumer trust by assuring them of product quality and safety, leading to increased sales and market competitiveness. Additionally, it opens up opportunities for manufacturers to participate in government tenders and contracts, which often require BIS certification. Furthermore, compliance with BIS standards can reduce product recalls and liability issues, promoting long-term business sustainability.",
      description: 'The BIS Registration Certificate confirms compliance with Indian quality and safety standards, enhancing consumer trust. It boosts competitiveness and opens opportunities for government contracts. This certification showcases a commitment to quality and safety.',
      link: 'Legal',
    },
    {
      image: 'images/inventory.jpg',
      title: 'LMPC Certification',
      passage1:"Overview of LMPC Registration: The LMPC (Laboratory and Manufacturing Processes Certification) Registration Certificate is an official recognition granted to laboratories and manufacturing facilities that meet specific quality and operational standards. This certification ensures that processes adhere to stringent guidelines, promoting accuracy, reliability, and safety in testing and manufacturing. It serves as a benchmark for quality assurance, helping organizations build credibility and trust with clients and stakeholders.",
      passage2:"Benefits of LMPC Registration: Obtaining an LMPC Registration Certificate offers several significant benefits. It enhances operational efficiency by standardizing processes and reducing errors, ultimately leading to cost savings. The certification also increases marketability, as it demonstrates compliance with industry standards, attracting more clients and opportunities for partnerships. Furthermore, it fosters a culture of continuous improvement, encouraging organizations to maintain high-quality practices.",
      description: 'The LMPC Registration Certificate certifies compliance with production and supply chain standards, enhancing efficiency. It builds consumer trust and strengthens brand reputation while opening partnership opportunities',
      link: 'Legal',
    },
    {
      image: 'images/custom.jpg',
      title: 'DGFT Registrations',
      passage1:"DGFT Portal Related Registrations and Certifications: The Directorate General of Foreign Trade (DGFT) plays a crucial role in regulating and facilitating international trade in India. The DGFT portal is a one-stop platform for various registrations and certifications essential for businesses engaged in exports and imports. Below is a detailed list of the types of registrations and certifications available through the DGFT, along with the associated benefits.",
      passage2:"Here’s a cohesive passage that captures all the key points from the provided content about DGFT registrations and certifications: The **Importer Exporter Code (IEC)** is a foundational requirement for any entity seeking to engage in international trade. It is essential for accessing various benefits, applying for necessary licenses, and interacting with customs authorities. In addition, the **Status Holder Certificate** recognizes exporters based on their performance, categorizing them into levels such as Star Export House and Super Star Export House. This certificate provides additional advantages, including reduced documentation, priority in customs clearances, and access to special incentive schemes. Another important certification is the **Export Promotion Capital Goods (EPCG) License**, which allows the import of capital goods at zero or reduced duty for the production of goods intended for export. This license facilitates the expansion of production capabilities and enhances competitiveness in the international market. Similarly, **Advance Authorization** permits duty-free import of inputs necessary for manufacturing export products, effectively reducing production costs and improving profitability for exporters.The **Duty Drawback Scheme** further supports exporters by reimbursing customs duties paid on imported goods that are subsequently exported, enhancing their cash flow through partial refunds of expenses. Various **Export Incentives Schemes**, such as the Merchandise Exports from India Scheme (MEIS) and the Services Exports from India Scheme (SEIS), are designed to promote exports by providing financial incentives that encourage competitiveness in global markets.Additionally, the **Single-Window Clearance for Exports** simplifies the documentation and approval processes for exporters, significantly reducing bureaucratic hurdles and accelerating the export process. For products subject to government control, a **Restricted Imports/Exports License** is required to ensure compliance with regulations and avoid penalties. Registration for **Foreign Trade Policy (FTP) Compliance** helps businesses stay informed about the latest regulations, allowing them to avail relevant benefits. Lastly, the **RCMC (Registration-Cum-Membership Certificate)**, issued by Export Promotion Councils for various commodities, grants access to support services and benefits under different schemes. By obtaining these essential registrations and certifications through the DGFT portal, businesses can streamline their international trade operations while enjoying numerous benefits that bolster their competitiveness and financial performance. This proactive approach ultimately creates a favorable environment for growth in global markets.",
      description: 'DGFT registrations and certifications, including the Importer Exporter Code (IEC), are essential for legal international trade in India. They enable market access and provide benefits like duty exemptions and financial assistance. These registrations help businesses expand their global presence and enhance competitiveness.',
      link: 'Legal', 
    },
    {
      image: 'images/custom.jpg',
      title: 'CUSTOM BROKER SERVICES',
      passage1:"",
      passage2:"",
      description: 'Iconikq International provides fast and reliable sea and air customs clearance. Our expert team ensures smooth processing with services like import/export clearance, documentation, shipment examination, and warehousing.',
      link: 'Legal', 
    },
    {
      image: 'images/custom.jpg',
      title: 'CUSTOM BROKER SERVICES',
      passage1:"",
      passage2:"",
      description: 'Iconikq International provides fast and reliable sea and air customs clearance. Our expert team ensures smooth processing with services like import/export clearance, documentation, shipment examination, and warehousing.',
      link: 'Legal', 
    },
    {
      image: 'images/custom.jpg',
      title: 'CUSTOM BROKER SERVICES',
      passage1:"",
      passage2:"",
      description: 'Iconikq International provides fast and reliable sea and air customs clearance. Our expert team ensures smooth processing with services like import/export clearance, documentation, shipment examination, and warehousing.',
      link: 'Legal', 
    },
    {
      image: 'images/custom.jpg',
      title: 'CUSTOM BROKER SERVICES',
      passage1:"",
      passage2:"",
      description: 'Iconikq International provides fast and reliable sea and air customs clearance. Our expert team ensures smooth processing with services like import/export clearance, documentation, shipment examination, and warehousing.',
      link: 'Legal', 
    },
    {
      image: 'images/custom.jpg',
      title: 'CUSTOM BROKER SERVICES',
      passage1:"",
      passage2:"",
      description: 'Iconikq International provides fast and reliable sea and air customs clearance. Our expert team ensures smooth processing with services like import/export clearance, documentation, shipment examination, and warehousing.',
      link: 'Legal', 
    },
    {
      image: 'images/custom.jpg',
      title: 'CUSTOM BROKER SERVICES',
      passage1:"",
      passage2:"",
      description: 'Iconikq International provides fast and reliable sea and air customs clearance. Our expert team ensures smooth processing with services like import/export clearance, documentation, shipment examination, and warehousing.',
      link: 'Legal', 
    },
    {
      image: 'images/custom.jpg',
      title: 'CUSTOM BROKER SERVICES',
      passage1:"",
      passage2:"",
      description: 'Iconikq International provides fast and reliable sea and air customs clearance. Our expert team ensures smooth processing with services like import/export clearance, documentation, shipment examination, and warehousing.',
      link: 'Legal', 
    },
    {
      image: 'images/custom.jpg',
      title: 'CUSTOM BROKER SERVICES',
      passage1:"",
      passage2:"",
      description: 'Iconikq International provides fast and reliable sea and air customs clearance. Our expert team ensures smooth processing with services like import/export clearance, documentation, shipment examination, and warehousing.',
      link: 'Legal', 
    },
    
  ];
