import Footer from "../layout/Footer"
import Navbar from "../layout/Navbar"
export const metadata = {
  title: "ICONIKQ | Drusti Portfoilo",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <>
 
  {/* component */}
  <Navbar/>
       {/* Name section */}
    <section className="flex flex-col items-center justify-center h-screen pt-8  -my-20 md:-mt-48 px-8">
      {/* style="height: 50vh" */}
      <div className="flex flex-col items-center justify-center text-center h-screen-half">
        {/* image */}
        <img
          className="md:hidden object-cover w-15 h-40 rounded-full mb-5 ring-2 ring-gray-500/50 ring-offset-[10px]"
          src="/images/drusti2.jpg"
          alt="Your Name Here"
        />
        <h1 className="text-5xl sm:text-6xl lg:text-9xl">Ms. Drishti Ruparel</h1>
        <h2 className="font-light text-4xl sm:text-5xl lg:text-8xl">
          Partner
        </h2>
      </div>
    </section>
    {/* /Name Section */}
    {/* image section */}
    <section className="flex items-center justify-between px-8 mb-20 tracking-wider">
      {/* Summary (left) */}
      <div className="flex flex-col w-full md:w-1/3 space-y-12 text-center md:text-left">
        <div className="flex flex-col px-10 md:px-20">
          <h3 className="text-xl font-bold">Skills</h3>
          <br />
          <span className="text-lg">Advertising</span>
          <span className="text-lg">Collaboration</span>
          <span className="text-lg">Communication</span>
          <span className="text-lg">Soft Skills</span>
          <span className="text-lg">Leadership</span>
        </div>

        <div className="px-10 md:px-20">
          <h3 className="text-xl font-bold">Summary</h3>
          <br />
          <p className="w-full md:w-2/3">
    A highly motivated and detail-oriented professional with a strong background in management and a proven track record in team collaboration and communication. Skilled in data analysis and proficient in Microsoft Office Suite, with the ability to adapt to new challenges and deliver results in fast-paced environments.
  </p>
        </div>
        <div className="px-10 md:px-20">
          <br />
          <h3 className="text-xl font-bold">Contact</h3>
          <a
            className="text-xl hover:text-blue-600"
            href="mailto:test@nomail.com"
          >
            drishti@iconikqinternational.com
          </a>
          <p>+91 9870176503</p>
        </div>
      </div>
      {/* image */}
      <img
        className="hidden md:block object-cover w-1/4 h-screen rounded-full ring-2 ring-gray-500/50 ring-offset-[30px]"
        src="/images/drusti3.jpg"
        alt="Your Name Here"
      />
      {/* statistics (right) */}
      <div className="hidden md:flex flex-col w-1/3 space-y-12 text-right">
        <div className="px-20">
          <h4 className="text-xl font-bold">Experience</h4>
          <br />
          <p className="text-6xl">+2</p>
        </div>
        <div className="px-20">
          <h4 className="text-xl font-bold">Projects</h4>
          <br />
          <p className="text-6xl">+25</p>
        </div>
        <div className="px-20">
          <h4 className="text-xl font-bold">Clients</h4>
          <br />
          <p className="text-6xl">+14</p>
        </div>
      </div>
    </section>
    {/* /image section */}
    <hr className="border-gray-400 mx-44" />
    {/* Resume */}
       {/* Experience Section */}
       <section className="px-20 mt-10">
        <h4 className="mb-8 text-3xl font-bold text-center md:text-left">
          Experience
        </h4>
        <div className="grid grid-cols-1 md:grid-cols-6 my-10">
          <div className="flex flex-col col-span-2 mb-4 md:mb-0">
            <h5 className="text-xl md:text-2xl font-bold">
              Partner
            </h5>
            <h6 className="text-lg font-bold">ICONIKQ INTERNATIONAL LLP</h6>
            <p>Jan 2022 - Present · 2 yrs 10 mos</p>
            <p>Mumbai, Maharashtra, India</p>
          </div>
          <div className="flex flex-col col-span-4">
            <p>
              Currently managing logistics operations and business strategies at ICONIKQ International LLP, ensuring efficient and transparent services. Key focus on freight forwarding, customs clearance, and transport management. Working closely with partners and stakeholders to deliver excellence in international and domestic logistics solutions.
            </p>
          </div>
        </div>
      </section>

      {/* Education Section */}
      <section className="px-20 mt-10">
        <h4 className="mb-8 text-3xl font-bold text-center md:text-left">
          Education
        </h4>
        <div className="grid grid-cols-1 md:grid-cols-6 my-10">
          <div className="flex flex-col col-span-2 mb-4 md:mb-0">
            <h5 className="text-xl md:text-2xl font-bold">
              Diploma in Business Management
            </h5>
            <h6 className="text-lg font-bold">NMIMS CDOE</h6>
            <p>Jan 2021 - Jan 2022</p>
            <p>Grade: A</p>
          </div>
          <div className="flex flex-col col-span-4">
            <p>
              Focused on business administration, marketing, and management. Participated in various activities, including the debate team, to hone communication and leadership skills.
            </p>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-6 my-10">
          <div className="flex flex-col col-span-2 mb-4 md:mb-0">
            <h5 className="text-xl md:text-2xl font-bold">
              Bachelor of Management Studies
            </h5>
            <h6 className="text-lg font-bold">S.M. Shetty College - Degree Section</h6>
            <p>Jun 2017 - Nov 2020</p>
            <p>Grade: A+</p>
          </div>
          <div className="flex flex-col col-span-4">
            <p>
              Specialized in Business Administration and Management. Actively participated in extracurriculars like badminton, dance, sports, and debates to enhance soft skills, leadership, and communication.
            </p>
          </div>
        </div>
      </section>
    <Footer/>
  </>



  )
}

export default page